filenames = [
"01.webp",
"1.webp",
"2.webp",
"2d-game-character.webp",
"3.webp",
"5.webp",
"5D solutions main.webp",
"5d status.webp",
"5d tech poster land.webp",
"5d tech poster.webp",
"22.webp",
"32cc5663-b0f5-4654-b0e5-696d19793608.webp",
"43.webp",
"45.webp",
"60d6a664-e25e-43af-8302-7876071d0d7e.webp",
"66.webp",
"72 me.webp",
"80.webp",
"1929.webp",
"3700_1_03.webp",
"business cards 2.webp",
"business cards 3.webp",
"business cards 5.webp",
"business cards 6.webp",
"business cards 7.webp",
"business cards 19.webp",
"business cards 222.webp",
"cannabis-mascot-logo-design_142989-494.webp",
"cat 2.webp",
"charater1.webp",
"CHROMA ELECTRONICS 2.webp",
"chroma flyer.webp",
"colorfull ui.webp",
"coming soon.webp",
"contructions.webp",
"cv1.webp",
"cyber ninjac mascot.webp",
"dark samurai moscot.webp",
"donedonadone.webp",
"dragon-ball-dragon-ball-z-kai-super-saiyan-blue-dragon-ball-super-wallpaper-preview.webp",
"dragon.webp",
"e-sports-snake-logo-venom-e-sport-logo_8319-1008.webp",
"ea6ac8_e3072cfc1720405e950c987ba6df1c74_mv2.webp",
"education.webp",
"finacial.webp",
"fiver gig wordpresss.webp",
"fiverf gig wordpresss.webp",
"fiverr wordpress second.webp",
"fiverr wordpress third.webp",
"flat ui copy.webp",
"Flyer (4) me.webp",
"flyer22.webp",
"flyer33.webp",
"FLYER111.webp",
"flyer332.webp",
"food poster-1.webp",
"football-1.webp",
"freelancer gig wordpresss.webp",
"front end website second.webp",
"frontwebs website designing one.webp",
"gamer-esport-mascot-logo-template_119810-165-min.webp",
"gamers-mascot-logo-design_142989-385-min.webp",
"gig 123 word press-min.webp",
"gig second page-min.webp",
"girl-charater-1-min.webp",
"GOKU SSJBLUE-min.webp",
"GOKU SSJBLUEs-min.webp",
"gr (3)-min.webp",
"graphic designer services-2-min.webp",
"guko mascot-min.webp",
"guko mascots-min.webp",
"Gym logo-min.webp",
"hamdan-template-min.webp",
"headshot moscot-min.webp",
"hello kitty-min.webp",
"hg-min.webp",
"ihtsham-min.webp",
"king-viking-illustration_148096-82-min.webp",
"king-viking-illustration_332261-278-min.webp",
"lightsaber mascot-min.webp",
"lion mascot-min.webp",
"little-ninja-mascot-esport-logo-design_194428-1100-min.webp",
"logo-1-min.webp",
"LOGO-2-min.webp",
"LOGO-3-min.webp",
"lumber mascot-min.webp",
"main-min.webp",
"master-panda-mascot-logo-esports-design-template_142989-589-min.webp",
"mCdT2mR2E70-min.webp",
"me_upscaled-min.webp",
"mech devil mascot-min.webp",
"mobile interface-min.webp",
"mockup 2 fiverr-min.webp",
"MockUp first fiverr-min.webp",
"MOCKUP SECOND FIVERR-min.webp",
"mockup Shirt pdf-min.webp",
"monkey moscot-min.webp",
"mustrerous masscot-min.webp",
"my cv 1080-min.webp",
"My resume-min.webp",
"NATIONAL GAMERZZ-min.webp",
"ninja mascot-min.webp",
"ninja-assassin-mascot-logo-game-sport-esport-team-illustration_23755-144-min.webp",
"ninja-ronin-samurai-with-wolf-mascot-sport-illustration-design-logo-esport-gaming-team-squad_120309-51-min.webp",
"ninja-sport-mascot-logo_119810-63-min.webp",
"ori_3703745_vttp2g77uu05vikzcsoijz49ruau6q2730773cib_lady-cyborg-esport-mascot-logo-design-min.webp",
"paladin-sport-mascot-logo_18228-1115-min.webp",
"Pet_1-min.webp",
"Pet_2-min.webp",
"Pet_3-min.webp",
"Pet_4-min.webp",
"Pet_5-min.webp",
"Pet_6-min.webp",
"Pet_7-min.webp",
"Pet_8-min.webp",
"Pet_9-min.webp",
"Pet_11-min.webp",
"Pet_12-min.webp",
"Pet_13-min.webp",
"Pet_14-min.webp",
"Pet_15-min.webp",
"Pet_16-min.webp",
"Pet_17-min.webp",
"Pet_18-min.webp",
"Pet_19-min.webp",
"Pet_20-min.webp",
"Pet_21-min.webp",
"pexels-karol-d-323645-min.webp",
"pexels-pixabay-270404-min.webp",
"pexels-pok-rie-1255372-min.webp",
"pexels-vera-emilie-andresen-bomstad-10328982-min.webp",
"Poster Frame PSD MockUp-min.webp",
"Presentation_Folder_Mockup_02-min.webp",
"psycho-esport-logo-mascot-design_122297-261-min.webp",
"rabbit mascot-min.webp",
"rainbow girl-min.webp",
"raster to pixel main fiverr-min.webp",
"retouching 1-min.webp",
"retouching 2-min.webp",
"retouching 3-min.webp",
"retouching idk-min.webp",
"ROMATIZE WINGS LOGO-min.webp",
"saloon pink-min.webp",
"self mascot-min.webp",
"shark mascot-min.webp",
"skin retouching-min.webp",
"skinless cat-min.webp",
"snake logovenom-min.webp",
"soldier-mascot-esport-logo_73313-305-min.webp",
"sos charater-min.webp",
"sos-charcters-min.webp",
"spartan-warrior-mascot-logo_12402-459-min.webp",
"stay calm and say Allahu Akbar-min.webp",
"supreme squad mascot logo-min.webp",
"swag panda mascot-min.webp",
"tornado-mascot-logo-esport-gaming_92675-548-min.webp",
"Untitled-1-min.webp",
"Untitled-2-min.webp",
"Untitled-3-min.webp",
"Untitled-4.webp",
"Untitled-6.webp",
"Untitled-11.webp",
"Untitled-13.webp",
"vector scene.webp",
"vector seen.webp",
"we are coming soon.webp",
"web apps designs second fiverr.webp",
"website app planning SECOND fiverr.webp",
"website app planning third fiverr.webp",
"website planning first fiverr.webp",
"website planning SECOND fiverr.webp",
"website planning THIRD fiverr.webp",
"What-Are-The-Basic-Steps-Of-Hiring-A-Web-Designing-Service-01.webp",
"What-is-Your-Website-Design-Process-Blog-Post-Feature-Image-36119-01.webp",
"WhatsApp Image 2022-07-20 at 6.55.07 PM.webp",
"white tiger mascot.webp",
"wolves mascot.webp",
"women-warrior-esport-mascot-logo_119810-809.webp",
"women-warrior-esport-mascot-logo_119810-813.webp",
"wordpress fiverr main.webp",
"wpb-background.webp"
]

html = ""
for i, filename in enumerate(filenames, 1):
    html += f"""            <!-- Portfolio Item {i} -->
            <div class="mosaic-item" data-image="assets/img/graphic-portfolio/{filename}">
                <img src="assets/img/graphic-portfolio/{filename}" alt="Graphic Design Work {i}">
                <div class="overlay">
                </div>
            </div>
            
"""

print(html)
